# Generated by Django 4.2.3 on 2023-08-01 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='solcitudes',
            new_name='soli',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 0, 22, 275046)),
        ),
    ]
