# Generated by Django 4.2.3 on 2023-08-01 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_solcitudes_solicitud_soli_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='soli',
            new_name='mantenimiento',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 5, 14, 873993)),
        ),
    ]
