# Generated by Django 4.2.3 on 2023-08-01 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_soli_solicitud_mantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('detalle_equipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('servicio_realizado', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
                ('tecnico', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('pendiente', 'Pendiente'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado'), ('en proceso', 'En proceso'), ('aceptado', 'Aceptado')], default='En espera', max_length=20)),
                ('prioridad', models.CharField(default='bajo', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 59, 39, 776535)),
        ),
    ]
