# Generated by Django 4.2.3 on 2023-08-01 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reporte_alter_solicitud_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='nombre_solicitante',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(21, 29, 16, 535369)),
        ),
    ]
