# Generated by Django 4.2.3 on 2023-08-06 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_descripcion_reporte_servicio_solicitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(21, 45, 34, 637955)),
        ),
    ]
