# Generated by Django 4.2.3 on 2023-08-06 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_solicitud_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(21, 47, 2, 265250)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(21, 47, 2, 265250)),
        ),
    ]
