# Generated by Django 4.2.3 on 2023-08-07 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_historial_alter_reporte_hora_alter_solicitud_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 51, 59, 710774)),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_final',
            field=models.TimeField(default=datetime.time(20, 51, 59, 710774)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 51, 59, 710774)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 51, 59, 695143)),
        ),
    ]
