# Generated by Django 4.2.3 on 2023-08-28 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_solicitud_apellidos_solicitud_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 53, 2, 511978)),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_final',
            field=models.TimeField(default=datetime.time(13, 53, 2, 511978)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 53, 2, 511978)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 53, 2, 511978)),
        ),
    ]
