# Generated by Django 4.2.3 on 2023-08-28 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_historial_hora_alter_historial_hora_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='apellido',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='nombre',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 3, 33, 398812)),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_final',
            field=models.TimeField(default=datetime.time(14, 3, 33, 398812)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 3, 33, 398812)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 3, 33, 398812)),
        ),
    ]
