# Generated by Django 4.2.3 on 2023-08-28 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_reporte_apellido_reporte_nombre_alter_historial_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='apellido',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 7, 7, 541403)),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_final',
            field=models.TimeField(default=datetime.time(14, 7, 7, 541403)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 7, 7, 541403)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 7, 7, 541403)),
        ),
    ]
