# Generated by Django 4.2.3 on 2023-08-28 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_historial_hora_alter_historial_hora_final_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='apellido',
            new_name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 45, 8, 778470)),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_final',
            field=models.TimeField(default=datetime.time(14, 45, 8, 778470)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 45, 8, 778470)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 45, 8, 778470)),
        ),
    ]
