# Generated by Django 4.2.3 on 2023-08-28 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_apellido_reporte_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='nombre_completo',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 24, 20, 856809)),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_final',
            field=models.TimeField(default=datetime.time(15, 24, 20, 856809)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 24, 20, 856809)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 24, 20, 856809)),
        ),
    ]
