# Generated by Django 4.2.3 on 2023-09-19 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_historial_nombre_completo_alter_historial_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='nombre',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 35, 54, 336455)),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_final',
            field=models.TimeField(default=datetime.time(12, 35, 54, 336455)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 35, 54, 334941)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 35, 54, 334941)),
        ),
    ]
