# Generated by Django 4.2.3 on 2023-09-21 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_diagnostico_nombre_alter_historial_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(19, 59, 46, 739280)),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_final',
            field=models.TimeField(default=datetime.time(19, 59, 46, 739280)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(default='En espera', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(19, 59, 46, 739280)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='En espera', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(default=datetime.time(19, 59, 46, 739280)),
        ),
    ]
