# Generated by Django 4.2.3 on 2023-09-25 21:38

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_historial_hora_alter_historial_hora_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 38, 12, 260525)),
        ),
        migrations.AlterField(
            model_name='historial',
            name='hora_final',
            field=models.TimeField(default=home.models.obtener_hora_actual),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 38, 12, 260525)),
        ),
    ]
