# Generated by Django 4.2.3 on 2023-09-25 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_historial_hora_alter_historial_hora_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(16, 1, 9, 69740)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(16, 1, 9, 69740)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='prioridad',
            field=models.CharField(default='Bajo', max_length=100),
        ),
    ]
