# Generated by Django 4.2.3 on 2023-09-26 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_historial_hora_alter_reporte_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(19, 48, 28, 938521)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(19, 48, 28, 937514)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='prioridad',
            field=models.CharField(default='Baja', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(default='Baja', max_length=100),
        ),
    ]
