# Generated by Django 4.2.3 on 2023-09-26 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_historial_hora_alter_reporte_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 1, 27, 13560)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 1, 27, 13560)),
        ),
    ]
